name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, repositories, metadata
          plugin_code: yes
          plugin_code_lines: 20
          plugin_code_languages: g0
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_lines: yes
          config_timezone: Europe/London
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: 76561199143007394
          plugin_steam_achievements_limit: 0
          plugin_steam_recent_games_limit: 5
          plugin_steam_games_limit: 10
